[phases.setup]
nixPkgs = ["nodejs_20", "ffmpeg", "streamlink"]

[phases.install]
cmds = [
  "npm ci --include=dev"
]

[phases.build]
cmds = ["npm run build:backend", "npm prune --omit=dev"]

[start]
cmd = "npm run start"
