[phases.setup]
nixPkgs = ["nodejs_20", "python311", "python311Packages.pip", "ffmpeg"]

[phases.install]
cmds = [
  "python -m pip install streamlink --break-system-packages",
  "npm ci --include=dev"
]

[phases.build]
cmds = ["npm run build:backend", "npm prune --omit=dev"]

[start]
cmd = "npm run start"
